# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(555, 419)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        widget.setFont(font)
        widget.setStyleSheet("")
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(110, 60, 111, 61))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(widget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 70, 111, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(widget)
        self.pushButton.setGeometry(QtCore.QRect(350, 70, 75, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(130, 330, 181, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(widget)
        self.label_3.setGeometry(QtCore.QRect(310, 340, 61, 33))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(widget)
        self.label_4.setGeometry(QtCore.QRect(380, 340, 32, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(widget)
        self.label_5.setGeometry(QtCore.QRect(170, 170, 211, 71))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(widget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 290, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(widget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 250, 171, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(widget)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 301, 21))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(widget)
        # QtCore.QMetaObject.connectSlotsByName(widget)
        self.pushButton.clicked.connect(widget.on_pushButton_clicked)
        self.pushButton_2.clicked.connect(widget.on_pushButton2_clicked)
        self.pushButton_3.clicked.connect(widget.show_dialog)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "健身日程管理软件"))
        self.label.setText(_translate("widget", "今天星期:"))
        self.pushButton.setText(_translate("widget", "查询"))
        self.label_2.setText(_translate("widget", "您已经坚持健身"))
        self.label_3.setText(_translate("widget", ""))
        self.label_4.setText(_translate("widget", "天了"))
        self.label_5.setText(_translate("widget", "今天是休息日！"))
        self.pushButton_2.setText(_translate("widget", "练完打卡"))
        self.pushButton_3.setText(_translate("widget", "上传训练照片"))
        self.label_6.setText(_translate("widget", "TextLabel"))
